#!/bin/bash

systemctl --user set-environment \
    PATH=/home/adam/bin:/usr/local/bin:/usr/X11R6/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin \
    ZDOTDIR=$ZDOTDIR \
    DISPLAY=:0 \
    XAUTHLOCALHOSTNAME=$host
