#!/bin/bash

if pgrep xfwm4; then
    echo "Found xfwm4; trying to replace with fluxbox"
    if pkill xfwm4; then
        fluxbox -log ~/.log/fluxbox.log >~/.log/xfwm-replacement.log 2>&1 &

        # Stop xfdesktop grabbing mouse clicks away from fluxbox
        xfdesktop -Q &
    else
        echo >&2 "Failed to kill xfwm4"
    fi
fi

# See also 50-keyboard

here=`dirname $0`
. $here/00-systemd-user-env

# N.B. we should only start after systemd --user environment is
# already set up.  This means no WantedBy=default.target in the unit.
systemctl --user start monitor-watcher.service
