#!/bin/sh

# Needed for proper urxvt alpha channel compositing

echo "### xcompmgr ..."

. $ZDOTDIR/lib/libproc.sh
. $ZDOTDIR/lib/libhost.sh

read_localhost_nickname
if [ "$localhost_nickname" == 'd600' ]; then
    echo "xcompmgr doesn't work on d600"
    exit 0
fi

detect_wm () {
    if [ -n "$DESKTOP_SESSION" ]; then
        wm="$DESKTOP_SESSION"
        echo "Detected window manager from \$DESKTOP_SESSION as $wm"
        return
    fi

    if executable_p wmctrl; then
        wm=`wmctrl -m | awk '/^Name: / { print $2 }'`
        if [ -n "$wm" ]; then
            echo "Detected window manager from wmctrl -m as $wm"
            return
        else
            echo "wmctrl -m failed" >&2
        fi
    else
        echo "wmctrl not executable" >&2
    fi
    
    echo "Warning: couldn't determine window manager" >&2
    wm=
}

detect_wm

if [[ "$wm" == *openbox* ]]; then
    if executable_p xcompmgr; then
        # shadows are buggy
        #xcompmgr -c -t-5 -l-5 -r4.2 -o.55 &
        echo "Launching xcompmgr ..."
        xcompmgr &
    else
        echo "Warning: xcompmgr not executable"
    fi
else
    echo "openbox not running; won't launch xcompmgr"
fi
