#!/bin/bash

# Needed for proper urxvt alpha channel compositing

. $ZDOTDIR/lib/libproc.sh
. $ZDOTDIR/lib/libhost.sh

read_localhost_nickname

case "$localhost_nickname" in
    d600)
        echo "xcompmgr doesn't work on d600"
        exit 0
        ;;
    # atlantic)
    #     echo "destabilises with F11?"
    #     exit 0
    #     ;;
esac

detect_wm () {
    if executable_p wmctrl; then
        wm=`wmctrl -m | awk '/^Name: / { print $2 }'`
        if [ -n "$wm" ]; then
            echo "Detected window manager from wmctrl -m as $wm"
            return
        else
            echo "wmctrl -m failed" >&2
        fi
    else
        echo "wmctrl not executable" >&2
    fi

    if [ -n "$DESKTOP_SESSION" ]; then
        wm="$DESKTOP_SESSION"
        # This could be 'xfce'
        echo "Detected window manager from \$DESKTOP_SESSION as $wm"
        return
    fi

    echo "Warning: couldn't determine window manager" >&2
    wm=
}

detect_wm

if [[ "$wm" =~ openbox|Fluxbox ]]; then
    if executable_p xcompmgr; then
        # shadows are buggy
        #xcompmgr -c -t-5 -l-5 -r4.2 -o.55 &
        echo "Launching xcompmgr ..."
        xcompmgr >/dev/null 2>&1 &
    else
        echo "Warning: xcompmgr not executable"
    fi
else
    echo "openbox not running; won't launch xcompmgr"
fi
