#!/bin/sh

# also change SESSION/.cfg-post.d/SESSION
for dir in $ZDOTDIR/.X_fonts $ZDOTDIR/.truetype; do
  if [ -d $dir ]; then
    if xset fp+ $dir; then
      echo "Added font dir $dir"
    else
      echo "Failed to add font dir $dir"
    fi
  else
    echo "Warning: $dir doesn't exist"
  fi
done
xset fp rehash

