#!/bin/bash

. $ZDOTDIR/lib/libproc.sh

if false && which clipit >&/dev/null; then
    run_unless_running clipit >& ~/.log/clipit.log &
elif which parcellite >&/dev/null; then
    run_unless_running parcellite >& ~/.log/parcellite.log &
else
    echo >&2 "Couldn't find clipboard manager to launch"
fi
