#!/bin/bash

. $ZDOTDIR/lib/libproc.sh

case "$WINDOWMANAGER" in
    i3)
        echo "# i3: skipping watchlogs-system-window"
        exit 0
        ;;
esac

if false && [ -z "$VNCDESKTOP" ]; then
    run_unless_running gkrellm -geometry -0+0 </dev/null &
fi
