#!/bin/sh

. $ZDOTDIR/lib/libproc.sh

kdeapps="knetworkmanager"
if [ -n "$KDE_FULL_SESSION" ]; then
  for app in $kdeapps; do
    echo "### $app ..."
    run_unless_running $app &
  done
else
  echo "not in kde, not launching: $kdeapps"
fi

