#!/bin/sh

. $ZDOTDIR/lib/libhost.sh

read_localhost_nickname

apply_keymap () {
    case "$localhost_nickname" in
        arabian)
            keymap-menu e7450-hacked
            ;;
        pacific)
            keymap-menu kinesis
            ;;
        atlantic)
            #keymap-menu gb
            ;;
        indian)
            keymap-menu w520-hacked
            ;;
        southern)
            keymap-menu d630-hacked
            ;;
        mediacentre)
            keymap-menu gyration-hacked
            ;;
        adriatic)
            keymap-menu n150-hacked
            ;;
        *)
            echo "WARNING: didn't know which keymap to use with $localhost_nickname" >&2
    esac
}

echo "### Xmodmap ..."
if [ -z "$VNCDESKTOP" ]; then
    apply_keymap
else
    echo "\$VNCDESKTOP is $VNCDESKTOP, not touching keymap"
fi

# GTK keybinding theme set in gconf-tweaks
