#!/bin/sh

. $ZDOTDIR/lib/libhost.sh

read_localhost_nickname

my_xmodmap () {
    backup=$HOME/.Xmodmap.orig.`hostname -s`
    if ! [ -e "$backup" ]; then
        xmodmap -pke > "$backup"
    fi

    case "$localhost_nickname" in
        atlantic)
            . $ZDOTDIR/.Xmodmap.d/lib/Kinesis     ;;
        d600)
            xmodmap ~/.keymaps/X11/Dell-D600-Adam ;;
        indian|pacific)
            xmodmap ~/.keymaps/X11/Dell-D620-Adam ;;
        southern)
            xmodmap ~/.keymaps/X11/Dell-D630-Adam ;;
        t23)
            xmodmap ~/.keymaps/X11/TP-T23-UK      ;;
        *)
            echo "WARNING: didn't know which keymap to use with $localhost_nickname" >&2
    esac
}

echo "### Xmodmap ..."
if [ -z "$VNCDESKTOP" ]; then
    my_xmodmap
else
    echo "\$VNCDESKTOP is $VNCDESKTOP, not running .Xmodmap hooks"
fi

# GTK keybinding theme set in gconf-tweaks
