#!/bin/sh

. $ZDOTDIR/lib/libproc.sh

# N.B. xscreensaver doesn't play nice with KDEWM=sawfish
if ! uname -r | grep -q xen; then
  run_if_executable xscreensaver -no-splash > ~/.xscreensaver.log 2>&1 &
fi

