#!/bin/sh

. ~/lib/libhost.sh
read_localhost_nickname

case "$localhost_nickname" in
    pacific)
        xset m 2 5
        ;;
    aegean)
        echo "Disabling tap to click"
        synclient MaxTapTime=0
        ;;
    *)
        xset m 2 4
        ;;
esac

if grep -rq '^ *Driver.*synaptics' /etc/X11/xorg.conf*; then
    echo "Synaptics touchpad detected in X11 config."
    if which synclient >/dev/null 2>&1; then
        echo "Tweaking parameters via synclient..."
        synclient VertScrollDelta=50 LeftEdge=130 RightEdge=970
        synclient TapButton1=0 MinSpeed=1.5 MaxSpeed=3
    else
        echo "synclient not found; cannot tweak parameters." >&2
        exit 1
    fi
else
    echo "Synaptics touchpad not detected in X11 config."
fi
