#!/bin/sh

. $ZDOTDIR/lib/libproc.sh

case "$WINDOWMANAGER" in
    i3)
        echo "# i3: skipping watchlogs-system-window"
        exit 0
        ;;
esac

echo "Skipping watchlogs-system-window in favour of fluxbox key binding"
#run_if_executable watchlogs-system-window >/dev/null &
