#!/bin/sh

. $ZDOTDIR/lib/libproc.sh

# N.B. xfdesktop takes care of wallpaper in XFCE but it steals clicks
# on the root window from fluxbox.
if pgrep xfdesktop >/dev/null; then
    xfdesktop -Q
fi

case "$WINDOWMANAGER" in
    i3)
        xsetroot -solid black
        exit 0
        ;;
    *)
        if [ -f ~/.background ]; then
            fbsetbg $(<~/.background)
        else
            echo "~/.background not found; not setting background."
        fi
        ;;
esac
