#!/bin/sh

. $ZDOTDIR/lib/libproc.sh

# N.B. xfdesktop takes care of wallpaper in XFCE

case "$WINDOWMANAGER" in
    i3)
        xsetroot -solid black
        exit 0
        ;;
    *)
        echo "Use fbsetbg to set backgrounds"
        ;;
esac

