#!/bin/bash

. $ZDOTDIR/lib/libhost.sh

read_localhost_nickname

# On indian at least, with a Kinesis keyboard, the evdev map
# is not the right one.
if [ "$localhost_nickname" != 'atlantic' ]; then
    #xmodmap $ZDOTDIR/.keymaps/X11/Kinesis-QWERTY
    setxkbmap -symbols 'pc+us+gb+adam(kinesis)' -geometry 'kinesis' -print | \
        xkbcomp -I/home/adam/.xkb - $DISPLAY 2>&1 | \
        egrep -v 'Warning: +No symbols defined for'
else
    # funny shit happens with evdev on atlantic, even on Fedora 15
    xmodmap $ZDOTDIR/.keymaps/X11/Kinesis-QWERTY-evdev
fi

xset r 64 # autorepeat Delete
xset r 66 # autorepeat left-hand minus

# kbdrate to work around https://bugs.freedesktop.org/show_bug.cgi?id=17500
