# Dark theme - matches gnome-terminal "Dark" and xfce4-terminal "dark" profiles
background #000000
foreground #ffffff

cursor                  #ff7f50
cursor_text_color       #43a7a7
selection_background    #264f78
selection_foreground    none

# Normal colors (0-7)
color0  #073642
color1  #dc322f
color2  #abbf21
color3  #b58900
color4  #268bd2
color5  #d33682
color6  #2aa198
color7  #eee8d5

# Bright colors (8-15)
color8  #a2a2a2
color9  #cb4b16
color10 #01ca82
color11 #d5d909
color12 #94b4ff
color13 #f007ce
color14 #56c4c4
color15 #fdf6e3
