# Light theme - matches gnome-terminal "Bright" and xfce4-terminal "light" profiles
background #ffffff
foreground #000000

cursor                  #ff7f50
cursor_text_color       #ffffff
selection_background    #add6ff
selection_foreground    none

# Normal colors (0-7)
color0  #ffffff
color1  #e55351
color2  #aac400
color3  #c59500
color4  #268bd2
color5  #d33682
color6  #56c4c4
color7  #949494

# Bright colors (8-15)
color8  #000000
color9  #ed0000
color10 #00aa07
color11 #dec100
color12 #002dcb
color13 #b00097
color14 #2aa198
color15 #505050
