#!/bin/bash

TIMEOUT=64

changed=

if lsusb | grep -q 'Dell.*E-Port Replicator'; then
    if [ "`nmcli radio wifi`" = 'enabled' ]; then
        logger "Connected to docking station; turning wifi off"
        nmcli radio wifi off
        changed=true
        # Always takes some time for the new config to settle, so don't
        # start exponential back-off too early.
        sleep 3
    fi
else
    if [ "`nmcli radio wifi`" = 'disabled' ]; then
        logger "Disconnected from docking station; turning wifi on"
        nmcli radio wifi on
        changed=true

        # Always takes some time for the new config to settle, so don't
        # start exponential back-off too early.  Wifi takes longer to settle.
        sleep 6
    fi
fi
