eDP connected 2880x1920+0+0 (normal left inverted right x axis y axis)
	CONNECTOR_ID: 73
   2880x1920     60.00*+
DisplayPort-7 connected primary 3840x2160+2880+0 (normal left inverted right x axis y axis)
	CONNECTOR_ID: 107
   3840x2160     60.00*+
HDMI-A-1 connected 1920x1080+6720+0 (normal left inverted right x axis y axis)
	CONNECTOR_ID: 120
   1920x1080     60.00*+
