#!/bin/bash

touch ~/.Xresources.d/local.rdb

~/bin/keymap-menu --install-symlinks

mkdir -p ~/.log

touch ~/.synergy-{client,server,domain}-name

here=$(dirname "$(realpath "$0")")
if ! "$here/../bin/fluxbox-gen-config"; then
    exit 1
fi

ggkg
