#!/bin/bash

touch ~/.Xresources.d/local.rdb

~/bin/keymap-menu --install-symlinks

mkdir -p ~/.log

touch ~/.synergy-{client,server,domain}-name

here=$(dirname $0)
mkdir -p ~/.fluxbox
keys=~/.fluxbox/keys

if erb $here/../.fluxbox/keys.erb > $keys; then
    echo "Generated $keys"
else
    exit 1
fi

ggkg
