#!/bin/bash

touch ~/.Xresources.d/local.rdb

# also change SESSION/.xsession
for dir in ~/.X_fonts ~/.truetype; do
  mkfontdir "$dir"
done

mkdir -p ~/.xsession-progs.d

for dir in $HOME/.kde{,4}/Autostart; do
    old=$dir/xsession-progs
    if [ -e $old ]; then
        if rm $old; then
            echo "Removed obsolete symlink $old"
        fi
    fi
done

ln -s .xsession-progs.d ~/.XSP

touch ~/.synergy-{client,server}-name
