#!/bin/bash

touch ~/.Xresources/local.rdb

mkdir -p ~/.xsession-progs.d

if which startkde >&/dev/null; then
  mkdir -p ~/.kde/Autostart
  cd ~/.kde/Autostart
  [ -e ~/.kde/Autostart/xsession-progs ] ||
    ln -s ../../.xsession-progs ~/.kde/Autostart/xsession-progs
fi

touch ~/.synergy-{client,server}-name
