#!/bin/bash

touch ~/.Xresources.d/local.rdb

~/bin/keymap-menu --install-symlinks

# also change SESSION/.xsession
for dir in ~/.X_fonts ~/.truetype; do
    if [ -e "$dir" ]; then
        mkfontdir "$dir"
    else
        echo "Warning: $dir does not exist; cannot run mkfontdir on it" >&2
    fi
done

mkdir -p ~/.xsession-progs.d ~/.log

for dir in $HOME/.kde{,4}/Autostart; do
    old=$dir/xsession-progs
    if [ -e $old ]; then
        if rm $old; then
            echo "Removed obsolete symlink $old"
        fi
    fi
done

[ -h ~/.XSP ] || ln -s .xsession-progs.d ~/.XSP

touch ~/.synergy-{client,server}-name
